/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './app.component.css.shim';
import * as import9 from './shared/header.component';
import * as import10 from './shared/header.component.ngfactory';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '../../../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import13 from './errors/error.component';
import * as import14 from './errors/error.component.ngfactory';
import * as import15 from '@ng-bootstrap/ng-bootstrap/tabset/tabset';
import * as import16 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/tabset/tabset.ngfactory';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from '@angular/router/src/router_outlet_map';
import * as import19 from '@angular/core/src/linker/component_factory_resolver';
import * as import20 from './errors/error.service';
import * as import21 from '@ng-bootstrap/ng-bootstrap/tabset/tabset-config';
import * as import22 from '@angular/core/src/linker/template_ref';
import * as import23 from '@angular/router/src/directives/router_outlet';
export class Wrapper_AppComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AppComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.AppComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AppComponent>;
  _AppComponent_0_3:Wrapper_AppComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent_Host0,renderType_AppComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'app-root',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AppComponent0(this.viewUtils,this,0,this._el_0);
    this._AppComponent_0_3 = new Wrapper_AppComponent();
    this.compView_0.create(this._AppComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._AppComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AppComponentNgFactory:import7.ComponentFactory<import0.AppComponent> = new import7.ComponentFactory<import0.AppComponent>('app-root',View_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = [import8.styles];
var renderType_AppComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_AppComponent,{});
export class View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _el_0:any;
  compView_0:import1.AppView<import9.HeaderComponent>;
  _HeaderComponent_0_3:import10.Wrapper_HeaderComponent;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  /*private*/ _vc_6:import11.ViewContainer;
  _RouterOutlet_6_5:import12.Wrapper_RouterOutlet;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  compView_9:import1.AppView<import13.ErrorComponent>;
  _ErrorComponent_9_3:import14.Wrapper_ErrorComponent;
  _text_10:any;
  _el_11:any;
  compView_11:import1.AppView<import15.NgbTabset>;
  _NgbTabset_11_3:import16.Wrapper_NgbTabset;
  _query_NgbTab_11_0:import17.QueryList<any>;
  _text_12:any;
  _el_13:any;
  _NgbTab_13_3:import16.Wrapper_NgbTab;
  _query_NgbTabContent_13_0:import17.QueryList<any>;
  _query_NgbTabTitle_13_1:import17.QueryList<any>;
  _text_14:any;
  _anchor_15:any;
  /*private*/ _vc_15:import11.ViewContainer;
  _TemplateRef_15_4:any;
  _NgbTabContent_15_5:import16.Wrapper_NgbTabContent;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _NgbTab_18_3:import16.Wrapper_NgbTab;
  _query_NgbTabContent_18_0:import17.QueryList<any>;
  _query_NgbTabTitle_18_1:import17.QueryList<any>;
  _text_19:any;
  _anchor_20:any;
  /*private*/ _vc_20:import11.ViewContainer;
  _TemplateRef_20_4:any;
  _NgbTabTitle_20_5:import16.Wrapper_NgbTabTitle;
  _text_21:any;
  _anchor_22:any;
  /*private*/ _vc_22:import11.ViewContainer;
  _TemplateRef_22_4:any;
  _NgbTabContent_22_5:import16.Wrapper_NgbTabContent;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _NgbTab_25_3:import16.Wrapper_NgbTab;
  _query_NgbTabContent_25_0:import17.QueryList<any>;
  _query_NgbTabTitle_25_1:import17.QueryList<any>;
  _text_26:any;
  _anchor_27:any;
  /*private*/ _vc_27:import11.ViewContainer;
  _TemplateRef_27_4:any;
  _NgbTabContent_27_5:import16.Wrapper_NgbTabContent;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent0,renderType_AppComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'app-header',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import10.View_HeaderComponent0(this.viewUtils,this,0,this._el_0);
    this._HeaderComponent_0_3 = new import10.Wrapper_HeaderComponent();
    this.compView_0.create(this._HeaderComponent_0_3.context);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'\n',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_2,'router-outlet',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_6 = new import11.ViewContainer(6,2,this,this._el_6);
    this._RouterOutlet_6_5 = new import12.Wrapper_RouterOutlet(this.parentView.injectorGet(import18.RouterOutletMap,this.parentIndex),this._vc_6.vcRef,this.parentView.injectorGet(import19.ComponentFactoryResolver,this.parentIndex),(null as any));
    this._text_7 = this.renderer.createText(this._el_2,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,parentRenderNode,'app-error',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_9 = new import14.View_ErrorComponent0(this.viewUtils,this,9,this._el_9);
    this._ErrorComponent_9_3 = new import14.Wrapper_ErrorComponent(this.parentView.injectorGet(import20.ErrorService,this.parentIndex));
    this.compView_9.create(this._ErrorComponent_9_3.context);
    this._text_10 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,parentRenderNode,'ngb-tabset',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_11 = new import16.View_NgbTabset0(this.viewUtils,this,11,this._el_11);
    this._NgbTabset_11_3 = new import16.Wrapper_NgbTabset(this.parentView.injectorGet(import21.NgbTabsetConfig,this.parentIndex));
    this._query_NgbTab_11_0 = new import17.QueryList<any>();
    this._text_12 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,(null as any),'ngb-tab',new import3.InlineArray2(2,'title','Simple'),(null as any));
    this._NgbTab_13_3 = new import16.Wrapper_NgbTab();
    this._query_NgbTabContent_13_0 = new import17.QueryList<any>();
    this._query_NgbTabTitle_13_1 = new import17.QueryList<any>();
    this._text_14 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._anchor_15 = this.renderer.createTemplateAnchor(this._el_13,(null as any));
    this._vc_15 = new import11.ViewContainer(15,13,this,this._anchor_15);
    this._TemplateRef_15_4 = new import22.TemplateRef_(this,15,this._anchor_15);
    this._NgbTabContent_15_5 = new import16.Wrapper_NgbTabContent(this._TemplateRef_15_4);
    this._text_16 = this.renderer.createText(this._el_13,'\n  ',(null as any));
    this._query_NgbTabContent_13_0.reset([this._NgbTabContent_15_5.context]);
    this._NgbTab_13_3.context.contentTpl = this._query_NgbTabContent_13_0.first;
    this._query_NgbTabTitle_13_1.reset(([] as any[]));
    this._NgbTab_13_3.context.titleTpl = this._query_NgbTabTitle_13_1.first;
    this._text_17 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,(null as any),'ngb-tab',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgbTab_18_3 = new import16.Wrapper_NgbTab();
    this._query_NgbTabContent_18_0 = new import17.QueryList<any>();
    this._query_NgbTabTitle_18_1 = new import17.QueryList<any>();
    this._text_19 = this.renderer.createText(this._el_18,'\n    ',(null as any));
    this._anchor_20 = this.renderer.createTemplateAnchor(this._el_18,(null as any));
    this._vc_20 = new import11.ViewContainer(20,18,this,this._anchor_20);
    this._TemplateRef_20_4 = new import22.TemplateRef_(this,20,this._anchor_20);
    this._NgbTabTitle_20_5 = new import16.Wrapper_NgbTabTitle(this._TemplateRef_20_4);
    this._text_21 = this.renderer.createText(this._el_18,'\n    ',(null as any));
    this._anchor_22 = this.renderer.createTemplateAnchor(this._el_18,(null as any));
    this._vc_22 = new import11.ViewContainer(22,18,this,this._anchor_22);
    this._TemplateRef_22_4 = new import22.TemplateRef_(this,22,this._anchor_22);
    this._NgbTabContent_22_5 = new import16.Wrapper_NgbTabContent(this._TemplateRef_22_4);
    this._text_23 = this.renderer.createText(this._el_18,'\n  ',(null as any));
    this._query_NgbTabContent_18_0.reset([this._NgbTabContent_22_5.context]);
    this._NgbTab_18_3.context.contentTpl = this._query_NgbTabContent_18_0.first;
    this._query_NgbTabTitle_18_1.reset([this._NgbTabTitle_20_5.context]);
    this._NgbTab_18_3.context.titleTpl = this._query_NgbTabTitle_18_1.first;
    this._text_24 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,(null as any),'ngb-tab',new import3.InlineArray2(2,'title','Disabled'),(null as any));
    this._NgbTab_25_3 = new import16.Wrapper_NgbTab();
    this._query_NgbTabContent_25_0 = new import17.QueryList<any>();
    this._query_NgbTabTitle_25_1 = new import17.QueryList<any>();
    this._text_26 = this.renderer.createText(this._el_25,'\n    ',(null as any));
    this._anchor_27 = this.renderer.createTemplateAnchor(this._el_25,(null as any));
    this._vc_27 = new import11.ViewContainer(27,25,this,this._anchor_27);
    this._TemplateRef_27_4 = new import22.TemplateRef_(this,27,this._anchor_27);
    this._NgbTabContent_27_5 = new import16.Wrapper_NgbTabContent(this._TemplateRef_27_4);
    this._text_28 = this.renderer.createText(this._el_25,'\n  ',(null as any));
    this._query_NgbTabContent_25_0.reset([this._NgbTabContent_27_5.context]);
    this._NgbTab_25_3.context.contentTpl = this._query_NgbTabContent_25_0.first;
    this._query_NgbTabTitle_25_1.reset(([] as any[]));
    this._NgbTab_25_3.context.titleTpl = this._query_NgbTabTitle_25_1.first;
    this._text_29 = this.renderer.createText((null as any),'\n',(null as any));
    this.compView_11.create(this._NgbTabset_11_3.context);
    this._text_30 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._anchor_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._anchor_20,
      this._text_21,
      this._anchor_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._anchor_27,
      this._text_28,
      this._text_29,
      this._text_30
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import9.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_3.context; }
    if (((token === import23.RouterOutlet) && (6 === requestNodeIndex))) { return this._RouterOutlet_6_5.context; }
    if (((token === import13.ErrorComponent) && (9 === requestNodeIndex))) { return this._ErrorComponent_9_3.context; }
    if (((token === import22.TemplateRef) && (15 === requestNodeIndex))) { return this._TemplateRef_15_4; }
    if (((token === import15.NgbTabContent) && (15 === requestNodeIndex))) { return this._NgbTabContent_15_5.context; }
    if (((token === import15.NgbTab) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._NgbTab_13_3.context; }
    if (((token === import22.TemplateRef) && (20 === requestNodeIndex))) { return this._TemplateRef_20_4; }
    if (((token === import15.NgbTabTitle) && (20 === requestNodeIndex))) { return this._NgbTabTitle_20_5.context; }
    if (((token === import22.TemplateRef) && (22 === requestNodeIndex))) { return this._TemplateRef_22_4; }
    if (((token === import15.NgbTabContent) && (22 === requestNodeIndex))) { return this._NgbTabContent_22_5.context; }
    if (((token === import15.NgbTab) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._NgbTab_18_3.context; }
    if (((token === import22.TemplateRef) && (27 === requestNodeIndex))) { return this._TemplateRef_27_4; }
    if (((token === import15.NgbTabContent) && (27 === requestNodeIndex))) { return this._NgbTabContent_27_5.context; }
    if (((token === import15.NgbTab) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._NgbTab_25_3.context; }
    if (((token === import15.NgbTabset) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._NgbTabset_11_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HeaderComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._RouterOutlet_6_5.ngDoCheck(this,this._el_6,throwOnChange);
    this._ErrorComponent_9_3.ngDoCheck(this,this._el_9,throwOnChange);
    this._NgbTabset_11_3.ngDoCheck(this,this._el_11,throwOnChange);
    const currVal_13_0_0:any = 'Simple';
    this._NgbTab_13_3.check_title(currVal_13_0_0,throwOnChange,false);
    this._NgbTab_13_3.ngDoCheck(this,this._el_13,throwOnChange);
    this._NgbTabContent_15_5.ngDoCheck(this,this._anchor_15,throwOnChange);
    this._NgbTab_18_3.ngDoCheck(this,this._el_18,throwOnChange);
    this._NgbTabTitle_20_5.ngDoCheck(this,this._anchor_20,throwOnChange);
    this._NgbTabContent_22_5.ngDoCheck(this,this._anchor_22,throwOnChange);
    const currVal_25_0_0:any = 'Disabled';
    this._NgbTab_25_3.check_title(currVal_25_0_0,throwOnChange,false);
    const currVal_25_0_1:any = true;
    this._NgbTab_25_3.check_disabled(currVal_25_0_1,throwOnChange,false);
    this._NgbTab_25_3.ngDoCheck(this,this._el_25,throwOnChange);
    this._NgbTabContent_27_5.ngDoCheck(this,this._anchor_27,throwOnChange);
    this._vc_6.detectChangesInNestedViews(throwOnChange);
    this._vc_15.detectChangesInNestedViews(throwOnChange);
    this._vc_20.detectChangesInNestedViews(throwOnChange);
    this._vc_22.detectChangesInNestedViews(throwOnChange);
    this._vc_27.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_NgbTab_11_0.dirty) {
        this._query_NgbTab_11_0.reset([
          this._NgbTab_13_3.context,
          this._NgbTab_18_3.context,
          this._NgbTab_25_3.context
        ]
        );
        this._NgbTabset_11_3.context.tabs = this._query_NgbTab_11_0;
        this._query_NgbTab_11_0.notifyOnChanges();
      }
      this._NgbTabset_11_3.context.ngAfterContentChecked();
    }
    this.compView_0.detectChanges(throwOnChange);
    this.compView_9.detectChanges(throwOnChange);
    this.compView_11.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_6.destroyNestedViews();
    this._vc_15.destroyNestedViews();
    this._vc_20.destroyNestedViews();
    this._vc_22.destroyNestedViews();
    this._vc_27.destroyNestedViews();
    this.compView_0.destroy();
    this.compView_9.destroy();
    this.compView_11.destroy();
    this._RouterOutlet_6_5.ngOnDestroy();
    this._NgbTabset_11_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 15)) { return new View_AppComponent1(this.viewUtils,this,15,this._anchor_15,this._vc_15); }
    if ((nodeIndex == 20)) { return new View_AppComponent2(this.viewUtils,this,20,this._anchor_20,this._vc_20); }
    if ((nodeIndex == 22)) { return new View_AppComponent3(this.viewUtils,this,22,this._anchor_22,this._vc_22); }
    if ((nodeIndex == 27)) { return new View_AppComponent4(this.viewUtils,this,27,this._anchor_27,this._vc_27); }
    return (null as any);
  }
}
class View_AppComponent1 extends import1.AppView<any> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_AppComponent1,renderType_AppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._text_0 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,(null as any),'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'Raw denim you probably haven\'t heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth\n      master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh\n      dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum\n      iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.',(null as any));
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.init(this._text_3,((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._text_0,ctx);
    cb(this._el_1,ctx);
    cb(this._text_3,ctx);
  }
}
class View_AppComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_AppComponent2,renderType_AppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'b',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Fancy',(null as any));
    this._text_2 = this.renderer.createText((null as any),' title',(null as any));
    this.init(this._text_2,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._text_2
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
    cb(this._text_2,ctx);
  }
}
class View_AppComponent3 extends import1.AppView<any> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_AppComponent3,renderType_AppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._text_0 = this.renderer.createText((null as any),'Food truck fixie locavore, accusamus mcsweeney\'s marfa nulla single-origin coffee squid.\n      ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,(null as any),'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table\n      craft beer twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl\n      cillum PBR. Homo nostrud organic, assumenda labore aesthetic magna delectus mollit. Keytar helvetica VHS salvia\n      yr, vero magna velit sapiente labore stumptown. Vegan fanny pack odio cillum wes anderson 8-bit, sustainable jean\n      shorts beard ut DIY ethical culpa terry richardson biodiesel. Art party scenester stumptown, tumblr butcher vero\n      sint qui sapiente accusamus tattooed echo park.',(null as any));
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.init(this._text_3,((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._text_0,ctx);
    cb(this._el_1,ctx);
    cb(this._text_3,ctx);
  }
}
class View_AppComponent4 extends import1.AppView<any> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_AppComponent4,renderType_AppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._text_0 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,(null as any),'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'Raw denim you probably haven\'t heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth\n      master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh\n      dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum\n      iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.',(null as any));
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.init(this._text_3,((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._text_0,ctx);
    cb(this._el_1,ctx);
    cb(this._text_3,ctx);
  }
}