/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@ng-bootstrap/ng-bootstrap/alert/alert.module';
import * as import4 from '@ng-bootstrap/ng-bootstrap/buttons/radio.module';
import * as import5 from '@ng-bootstrap/ng-bootstrap/collapse/collapse.module';
import * as import6 from '@ng-bootstrap/ng-bootstrap/progressbar/progressbar.module';
import * as import7 from '@ng-bootstrap/ng-bootstrap/tooltip/tooltip.module';
import * as import8 from '@ng-bootstrap/ng-bootstrap/typeahead/typeahead.module';
import * as import9 from '@ng-bootstrap/ng-bootstrap/accordion/accordion.module';
import * as import10 from '@ng-bootstrap/ng-bootstrap/carousel/carousel.module';
import * as import11 from '@angular/forms/src/directives';
import * as import12 from '@angular/forms/src/form_providers';
import * as import13 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker.module';
import * as import14 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown.module';
import * as import15 from '@ng-bootstrap/ng-bootstrap/modal/modal.module';
import * as import16 from '@ng-bootstrap/ng-bootstrap/pagination/pagination.module';
import * as import17 from '@ng-bootstrap/ng-bootstrap/popover/popover.module';
import * as import18 from '@ng-bootstrap/ng-bootstrap/rating/rating.module';
import * as import19 from '@ng-bootstrap/ng-bootstrap/tabset/tabset.module';
import * as import20 from '@ng-bootstrap/ng-bootstrap/timepicker/timepicker.module';
import * as import21 from '@ng-bootstrap/ng-bootstrap/index';
import * as import22 from '@angular/router/src/router_module';
import * as import23 from '@angular/core/src/application_module';
import * as import24 from '@angular/platform-browser/src/browser';
import * as import25 from '@angular/http/src/http_module';
import * as import26 from './messages/message.module';
import * as import27 from '@angular/common/src/localization';
import * as import28 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import29 from '@ng-bootstrap/ng-bootstrap/modal/modal-stack';
import * as import30 from '@ng-bootstrap/ng-bootstrap/modal/modal';
import * as import31 from '@ng-bootstrap/ng-bootstrap/alert/alert-config';
import * as import32 from '@ng-bootstrap/ng-bootstrap/progressbar/progressbar-config';
import * as import33 from '@ng-bootstrap/ng-bootstrap/tooltip/tooltip-config';
import * as import34 from '@ng-bootstrap/ng-bootstrap/typeahead/typeahead-config';
import * as import35 from '@ng-bootstrap/ng-bootstrap/accordion/accordion-config';
import * as import36 from '@ng-bootstrap/ng-bootstrap/carousel/carousel-config';
import * as import37 from '@ng-bootstrap/ng-bootstrap/datepicker/ngb-calendar';
import * as import38 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker-i18n';
import * as import39 from '@ng-bootstrap/ng-bootstrap/datepicker/ngb-date-parser-formatter';
import * as import40 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker-service';
import * as import41 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker-config';
import * as import42 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown-config';
import * as import43 from '@ng-bootstrap/ng-bootstrap/pagination/pagination-config';
import * as import44 from '@ng-bootstrap/ng-bootstrap/popover/popover-config';
import * as import45 from '@ng-bootstrap/ng-bootstrap/rating/rating-config';
import * as import46 from '@ng-bootstrap/ng-bootstrap/tabset/tabset-config';
import * as import47 from '@ng-bootstrap/ng-bootstrap/timepicker/timepicker-config';
import * as import48 from '@angular/core/src/application_init';
import * as import49 from '@angular/core/src/testability/testability';
import * as import50 from '@angular/core/src/application_ref';
import * as import51 from '@angular/core/src/linker/compiler';
import * as import52 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import53 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import54 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import55 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import56 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import57 from '@angular/core/src/linker/view_utils';
import * as import58 from '@angular/platform-browser/src/browser/title';
import * as import59 from '@angular/http/src/backends/browser_xhr';
import * as import60 from '@angular/http/src/base_response_options';
import * as import61 from '@angular/http/src/backends/xhr_backend';
import * as import62 from '@angular/http/src/base_request_options';
import * as import63 from './errors/error.service';
import * as import64 from './messages/message.service';
import * as import65 from '@angular/common/src/location/location';
import * as import66 from '@angular/router/src/url_tree';
import * as import67 from '@angular/router/src/router_outlet_map';
import * as import68 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import69 from '@angular/router/src/router_preloader';
import * as import70 from './auth/auth.service';
import * as import71 from '@angular/core/src/di/injector';
import * as import72 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory';
import * as import73 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/tooltip/tooltip.ngfactory';
import * as import74 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead-window.ngfactory';
import * as import75 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.ngfactory';
import * as import76 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-backdrop.ngfactory';
import * as import77 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-window.ngfactory';
import * as import78 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/popover/popover.ngfactory';
import * as import79 from './messages/messages.component.ngfactory';
import * as import80 from './auth/authentication.component.ngfactory';
import * as import81 from './app.component.ngfactory';
import * as import82 from '@angular/core/src/application_tokens';
import * as import83 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import84 from '@angular/platform-browser/src/dom/events/key_events';
import * as import85 from '@angular/core/src/zone/ng_zone';
import * as import86 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import87 from '@angular/common/src/location/platform_location';
import * as import88 from '@angular/common/src/location/location_strategy';
import * as import89 from './messages/messages.component';
import * as import90 from './auth/authentication.component';
import * as import91 from '@angular/router/src/url_handling_strategy';
import * as import92 from '@angular/router/src/router';
import * as import93 from '@angular/core/src/console';
import * as import94 from '@angular/core/src/i18n/tokens';
import * as import95 from '@angular/core/src/error_handler';
import * as import96 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import97 from '@angular/platform-browser/src/dom/animation_driver';
import * as import98 from '@angular/core/src/render/api';
import * as import99 from '@angular/core/src/security';
import * as import100 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import101 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import102 from '@angular/http/src/interfaces';
import * as import103 from '@angular/http/src/http';
import * as import104 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import105 from '@angular/router/src/router_config_loader';
import * as import106 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _NgbAlertModule_1:import3.NgbAlertModule;
  _NgbButtonsModule_2:import4.NgbButtonsModule;
  _NgbCollapseModule_3:import5.NgbCollapseModule;
  _NgbProgressbarModule_4:import6.NgbProgressbarModule;
  _NgbTooltipModule_5:import7.NgbTooltipModule;
  _NgbTypeaheadModule_6:import8.NgbTypeaheadModule;
  _NgbAccordionModule_7:import9.NgbAccordionModule;
  _NgbCarouselModule_8:import10.NgbCarouselModule;
  _InternalFormsSharedModule_9:import11.InternalFormsSharedModule;
  _FormsModule_10:import12.FormsModule;
  _NgbDatepickerModule_11:import13.NgbDatepickerModule;
  _NgbDropdownModule_12:import14.NgbDropdownModule;
  _NgbModalModule_13:import15.NgbModalModule;
  _NgbPaginationModule_14:import16.NgbPaginationModule;
  _NgbPopoverModule_15:import17.NgbPopoverModule;
  _NgbRatingModule_16:import18.NgbRatingModule;
  _NgbTabsetModule_17:import19.NgbTabsetModule;
  _NgbTimepickerModule_18:import20.NgbTimepickerModule;
  _NgbRootModule_19:import21.NgbRootModule;
  _ROUTER_FORROOT_GUARD_20:any;
  _RouterModule_21:import22.RouterModule;
  _ApplicationModule_22:import23.ApplicationModule;
  _BrowserModule_23:import24.BrowserModule;
  _HttpModule_24:import25.HttpModule;
  _MessageModule_25:import26.MessageModule;
  _AppModule_26:import1.AppModule;
  __LOCALE_ID_27:any;
  __NgLocalization_28:import27.NgLocaleLocalization;
  __RadioControlRegistry_29:import28.RadioControlRegistry;
  __NgbModalStack_30:import29.NgbModalStack;
  __NgbModal_31:import30.NgbModal;
  __NgbAlertConfig_32:import31.NgbAlertConfig;
  __NgbProgressbarConfig_33:import32.NgbProgressbarConfig;
  __NgbTooltipConfig_34:import33.NgbTooltipConfig;
  __NgbTypeaheadConfig_35:import34.NgbTypeaheadConfig;
  __NgbAccordionConfig_36:import35.NgbAccordionConfig;
  __NgbCarouselConfig_37:import36.NgbCarouselConfig;
  __NgbCalendar_38:import37.NgbCalendarGregorian;
  __NgbDatepickerI18n_39:import38.NgbDatepickerI18nDefault;
  __NgbDateParserFormatter_40:import39.NgbDateISOParserFormatter;
  __NgbDatepickerService_41:import40.NgbDatepickerService;
  __NgbDatepickerConfig_42:import41.NgbDatepickerConfig;
  __NgbDropdownConfig_43:import42.NgbDropdownConfig;
  __NgbPaginationConfig_44:import43.NgbPaginationConfig;
  __NgbPopoverConfig_45:import44.NgbPopoverConfig;
  __NgbRatingConfig_46:import45.NgbRatingConfig;
  __NgbTabsetConfig_47:import46.NgbTabsetConfig;
  __NgbTimepickerConfig_48:import47.NgbTimepickerConfig;
  _ErrorHandler_49:any;
  _ApplicationInitStatus_50:import48.ApplicationInitStatus;
  _Testability_51:import49.Testability;
  _ApplicationRef__52:import50.ApplicationRef_;
  __ApplicationRef_53:any;
  __Compiler_54:import51.Compiler;
  __APP_ID_55:any;
  __DOCUMENT_56:any;
  __HAMMER_GESTURE_CONFIG_57:import52.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_58:any[];
  __EventManager_59:import53.EventManager;
  __DomSharedStylesHost_60:import54.DomSharedStylesHost;
  __AnimationDriver_61:any;
  __DomRootRenderer_62:import55.DomRootRenderer_;
  __RootRenderer_63:any;
  __DomSanitizer_64:import56.DomSanitizerImpl;
  __Sanitizer_65:any;
  __ViewUtils_66:import57.ViewUtils;
  __IterableDiffers_67:any;
  __KeyValueDiffers_68:any;
  __SharedStylesHost_69:any;
  __Title_70:import58.Title;
  __BrowserXhr_71:import59.BrowserXhr;
  __ResponseOptions_72:import60.BaseResponseOptions;
  __XSRFStrategy_73:any;
  __XHRBackend_74:import61.XHRBackend;
  __RequestOptions_75:import62.BaseRequestOptions;
  __Http_76:any;
  __ErrorService_77:import63.ErrorService;
  __MessageService_78:import64.MessageService;
  __ROUTER_CONFIGURATION_79:any;
  __LocationStrategy_80:any;
  __Location_81:import65.Location;
  __UrlSerializer_82:import66.DefaultUrlSerializer;
  __RouterOutletMap_83:import67.RouterOutletMap;
  __NgModuleFactoryLoader_84:import68.SystemJsNgModuleLoader;
  __ROUTES_85:any[];
  __Router_86:any;
  __ActivatedRoute_87:any;
  _NoPreloading_88:import69.NoPreloading;
  _PreloadingStrategy_89:any;
  _RouterPreloader_90:import69.RouterPreloader;
  __PreloadAllModules_91:import69.PreloadAllModules;
  __ROUTER_INITIALIZER_92:any;
  __APP_BOOTSTRAP_LISTENER_93:any[];
  __AuthService_94:import70.AuthService;
  constructor(parent:import71.Injector) {
    super(parent,[
      import72.NgbAlertNgFactory,
      import73.NgbTooltipWindowNgFactory,
      import74.NgbTypeaheadWindowNgFactory,
      import75.NgbDatepickerNgFactory,
      import76.NgbModalBackdropNgFactory,
      import77.NgbModalWindowNgFactory,
      import78.NgbPopoverWindowNgFactory,
      import79.MessagesComponentNgFactory,
      import80.AuthenticationComponentNgFactory,
      import81.AppComponentNgFactory
    ]
    ,[import81.AppComponentNgFactory]);
  }
  get _LOCALE_ID_27():any {
    if ((this.__LOCALE_ID_27 == null)) { (this.__LOCALE_ID_27 = 'en-US'); }
    return this.__LOCALE_ID_27;
  }
  get _NgLocalization_28():import27.NgLocaleLocalization {
    if ((this.__NgLocalization_28 == null)) { (this.__NgLocalization_28 = new import27.NgLocaleLocalization(this._LOCALE_ID_27)); }
    return this.__NgLocalization_28;
  }
  get _RadioControlRegistry_29():import28.RadioControlRegistry {
    if ((this.__RadioControlRegistry_29 == null)) { (this.__RadioControlRegistry_29 = new import28.RadioControlRegistry()); }
    return this.__RadioControlRegistry_29;
  }
  get _NgbModalStack_30():import29.NgbModalStack {
    if ((this.__NgbModalStack_30 == null)) { (this.__NgbModalStack_30 = new import29.NgbModalStack()); }
    return this.__NgbModalStack_30;
  }
  get _NgbModal_31():import30.NgbModal {
    if ((this.__NgbModal_31 == null)) { (this.__NgbModal_31 = new import30.NgbModal(this,this,this._NgbModalStack_30)); }
    return this.__NgbModal_31;
  }
  get _NgbAlertConfig_32():import31.NgbAlertConfig {
    if ((this.__NgbAlertConfig_32 == null)) { (this.__NgbAlertConfig_32 = new import31.NgbAlertConfig()); }
    return this.__NgbAlertConfig_32;
  }
  get _NgbProgressbarConfig_33():import32.NgbProgressbarConfig {
    if ((this.__NgbProgressbarConfig_33 == null)) { (this.__NgbProgressbarConfig_33 = new import32.NgbProgressbarConfig()); }
    return this.__NgbProgressbarConfig_33;
  }
  get _NgbTooltipConfig_34():import33.NgbTooltipConfig {
    if ((this.__NgbTooltipConfig_34 == null)) { (this.__NgbTooltipConfig_34 = new import33.NgbTooltipConfig()); }
    return this.__NgbTooltipConfig_34;
  }
  get _NgbTypeaheadConfig_35():import34.NgbTypeaheadConfig {
    if ((this.__NgbTypeaheadConfig_35 == null)) { (this.__NgbTypeaheadConfig_35 = new import34.NgbTypeaheadConfig()); }
    return this.__NgbTypeaheadConfig_35;
  }
  get _NgbAccordionConfig_36():import35.NgbAccordionConfig {
    if ((this.__NgbAccordionConfig_36 == null)) { (this.__NgbAccordionConfig_36 = new import35.NgbAccordionConfig()); }
    return this.__NgbAccordionConfig_36;
  }
  get _NgbCarouselConfig_37():import36.NgbCarouselConfig {
    if ((this.__NgbCarouselConfig_37 == null)) { (this.__NgbCarouselConfig_37 = new import36.NgbCarouselConfig()); }
    return this.__NgbCarouselConfig_37;
  }
  get _NgbCalendar_38():import37.NgbCalendarGregorian {
    if ((this.__NgbCalendar_38 == null)) { (this.__NgbCalendar_38 = new import37.NgbCalendarGregorian()); }
    return this.__NgbCalendar_38;
  }
  get _NgbDatepickerI18n_39():import38.NgbDatepickerI18nDefault {
    if ((this.__NgbDatepickerI18n_39 == null)) { (this.__NgbDatepickerI18n_39 = new import38.NgbDatepickerI18nDefault()); }
    return this.__NgbDatepickerI18n_39;
  }
  get _NgbDateParserFormatter_40():import39.NgbDateISOParserFormatter {
    if ((this.__NgbDateParserFormatter_40 == null)) { (this.__NgbDateParserFormatter_40 = new import39.NgbDateISOParserFormatter()); }
    return this.__NgbDateParserFormatter_40;
  }
  get _NgbDatepickerService_41():import40.NgbDatepickerService {
    if ((this.__NgbDatepickerService_41 == null)) { (this.__NgbDatepickerService_41 = new import40.NgbDatepickerService(this._NgbCalendar_38)); }
    return this.__NgbDatepickerService_41;
  }
  get _NgbDatepickerConfig_42():import41.NgbDatepickerConfig {
    if ((this.__NgbDatepickerConfig_42 == null)) { (this.__NgbDatepickerConfig_42 = new import41.NgbDatepickerConfig()); }
    return this.__NgbDatepickerConfig_42;
  }
  get _NgbDropdownConfig_43():import42.NgbDropdownConfig {
    if ((this.__NgbDropdownConfig_43 == null)) { (this.__NgbDropdownConfig_43 = new import42.NgbDropdownConfig()); }
    return this.__NgbDropdownConfig_43;
  }
  get _NgbPaginationConfig_44():import43.NgbPaginationConfig {
    if ((this.__NgbPaginationConfig_44 == null)) { (this.__NgbPaginationConfig_44 = new import43.NgbPaginationConfig()); }
    return this.__NgbPaginationConfig_44;
  }
  get _NgbPopoverConfig_45():import44.NgbPopoverConfig {
    if ((this.__NgbPopoverConfig_45 == null)) { (this.__NgbPopoverConfig_45 = new import44.NgbPopoverConfig()); }
    return this.__NgbPopoverConfig_45;
  }
  get _NgbRatingConfig_46():import45.NgbRatingConfig {
    if ((this.__NgbRatingConfig_46 == null)) { (this.__NgbRatingConfig_46 = new import45.NgbRatingConfig()); }
    return this.__NgbRatingConfig_46;
  }
  get _NgbTabsetConfig_47():import46.NgbTabsetConfig {
    if ((this.__NgbTabsetConfig_47 == null)) { (this.__NgbTabsetConfig_47 = new import46.NgbTabsetConfig()); }
    return this.__NgbTabsetConfig_47;
  }
  get _NgbTimepickerConfig_48():import47.NgbTimepickerConfig {
    if ((this.__NgbTimepickerConfig_48 == null)) { (this.__NgbTimepickerConfig_48 = new import47.NgbTimepickerConfig()); }
    return this.__NgbTimepickerConfig_48;
  }
  get _ApplicationRef_53():any {
    if ((this.__ApplicationRef_53 == null)) { (this.__ApplicationRef_53 = this._ApplicationRef__52); }
    return this.__ApplicationRef_53;
  }
  get _Compiler_54():import51.Compiler {
    if ((this.__Compiler_54 == null)) { (this.__Compiler_54 = new import51.Compiler()); }
    return this.__Compiler_54;
  }
  get _APP_ID_55():any {
    if ((this.__APP_ID_55 == null)) { (this.__APP_ID_55 = import82._appIdRandomProviderFactory()); }
    return this.__APP_ID_55;
  }
  get _DOCUMENT_56():any {
    if ((this.__DOCUMENT_56 == null)) { (this.__DOCUMENT_56 = import24._document()); }
    return this.__DOCUMENT_56;
  }
  get _HAMMER_GESTURE_CONFIG_57():import52.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_57 == null)) { (this.__HAMMER_GESTURE_CONFIG_57 = new import52.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_57;
  }
  get _EVENT_MANAGER_PLUGINS_58():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_58 == null)) { (this.__EVENT_MANAGER_PLUGINS_58 = [
      new import83.DomEventsPlugin(),
      new import84.KeyEventsPlugin(),
      new import52.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_57)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_58;
  }
  get _EventManager_59():import53.EventManager {
    if ((this.__EventManager_59 == null)) { (this.__EventManager_59 = new import53.EventManager(this._EVENT_MANAGER_PLUGINS_58,this.parent.get(import85.NgZone))); }
    return this.__EventManager_59;
  }
  get _DomSharedStylesHost_60():import54.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_60 == null)) { (this.__DomSharedStylesHost_60 = new import54.DomSharedStylesHost(this._DOCUMENT_56)); }
    return this.__DomSharedStylesHost_60;
  }
  get _AnimationDriver_61():any {
    if ((this.__AnimationDriver_61 == null)) { (this.__AnimationDriver_61 = import24._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_61;
  }
  get _DomRootRenderer_62():import55.DomRootRenderer_ {
    if ((this.__DomRootRenderer_62 == null)) { (this.__DomRootRenderer_62 = new import55.DomRootRenderer_(this._DOCUMENT_56,this._EventManager_59,this._DomSharedStylesHost_60,this._AnimationDriver_61,this._APP_ID_55)); }
    return this.__DomRootRenderer_62;
  }
  get _RootRenderer_63():any {
    if ((this.__RootRenderer_63 == null)) { (this.__RootRenderer_63 = import86._createConditionalRootRenderer(this._DomRootRenderer_62,this.parent.get(import86.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_63;
  }
  get _DomSanitizer_64():import56.DomSanitizerImpl {
    if ((this.__DomSanitizer_64 == null)) { (this.__DomSanitizer_64 = new import56.DomSanitizerImpl()); }
    return this.__DomSanitizer_64;
  }
  get _Sanitizer_65():any {
    if ((this.__Sanitizer_65 == null)) { (this.__Sanitizer_65 = this._DomSanitizer_64); }
    return this.__Sanitizer_65;
  }
  get _ViewUtils_66():import57.ViewUtils {
    if ((this.__ViewUtils_66 == null)) { (this.__ViewUtils_66 = new import57.ViewUtils(this._RootRenderer_63,this._Sanitizer_65)); }
    return this.__ViewUtils_66;
  }
  get _IterableDiffers_67():any {
    if ((this.__IterableDiffers_67 == null)) { (this.__IterableDiffers_67 = import23._iterableDiffersFactory()); }
    return this.__IterableDiffers_67;
  }
  get _KeyValueDiffers_68():any {
    if ((this.__KeyValueDiffers_68 == null)) { (this.__KeyValueDiffers_68 = import23._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_68;
  }
  get _SharedStylesHost_69():any {
    if ((this.__SharedStylesHost_69 == null)) { (this.__SharedStylesHost_69 = this._DomSharedStylesHost_60); }
    return this.__SharedStylesHost_69;
  }
  get _Title_70():import58.Title {
    if ((this.__Title_70 == null)) { (this.__Title_70 = new import58.Title()); }
    return this.__Title_70;
  }
  get _BrowserXhr_71():import59.BrowserXhr {
    if ((this.__BrowserXhr_71 == null)) { (this.__BrowserXhr_71 = new import59.BrowserXhr()); }
    return this.__BrowserXhr_71;
  }
  get _ResponseOptions_72():import60.BaseResponseOptions {
    if ((this.__ResponseOptions_72 == null)) { (this.__ResponseOptions_72 = new import60.BaseResponseOptions()); }
    return this.__ResponseOptions_72;
  }
  get _XSRFStrategy_73():any {
    if ((this.__XSRFStrategy_73 == null)) { (this.__XSRFStrategy_73 = import25._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_73;
  }
  get _XHRBackend_74():import61.XHRBackend {
    if ((this.__XHRBackend_74 == null)) { (this.__XHRBackend_74 = new import61.XHRBackend(this._BrowserXhr_71,this._ResponseOptions_72,this._XSRFStrategy_73)); }
    return this.__XHRBackend_74;
  }
  get _RequestOptions_75():import62.BaseRequestOptions {
    if ((this.__RequestOptions_75 == null)) { (this.__RequestOptions_75 = new import62.BaseRequestOptions()); }
    return this.__RequestOptions_75;
  }
  get _Http_76():any {
    if ((this.__Http_76 == null)) { (this.__Http_76 = import25.httpFactory(this._XHRBackend_74,this._RequestOptions_75)); }
    return this.__Http_76;
  }
  get _ErrorService_77():import63.ErrorService {
    if ((this.__ErrorService_77 == null)) { (this.__ErrorService_77 = new import63.ErrorService()); }
    return this.__ErrorService_77;
  }
  get _MessageService_78():import64.MessageService {
    if ((this.__MessageService_78 == null)) { (this.__MessageService_78 = new import64.MessageService(this._Http_76,this._ErrorService_77)); }
    return this.__MessageService_78;
  }
  get _ROUTER_CONFIGURATION_79():any {
    if ((this.__ROUTER_CONFIGURATION_79 == null)) { (this.__ROUTER_CONFIGURATION_79 = {}); }
    return this.__ROUTER_CONFIGURATION_79;
  }
  get _LocationStrategy_80():any {
    if ((this.__LocationStrategy_80 == null)) { (this.__LocationStrategy_80 = import22.provideLocationStrategy(this.parent.get(import87.PlatformLocation),this.parent.get(import88.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_79)); }
    return this.__LocationStrategy_80;
  }
  get _Location_81():import65.Location {
    if ((this.__Location_81 == null)) { (this.__Location_81 = new import65.Location(this._LocationStrategy_80)); }
    return this.__Location_81;
  }
  get _UrlSerializer_82():import66.DefaultUrlSerializer {
    if ((this.__UrlSerializer_82 == null)) { (this.__UrlSerializer_82 = new import66.DefaultUrlSerializer()); }
    return this.__UrlSerializer_82;
  }
  get _RouterOutletMap_83():import67.RouterOutletMap {
    if ((this.__RouterOutletMap_83 == null)) { (this.__RouterOutletMap_83 = new import67.RouterOutletMap()); }
    return this.__RouterOutletMap_83;
  }
  get _NgModuleFactoryLoader_84():import68.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_84 == null)) { (this.__NgModuleFactoryLoader_84 = new import68.SystemJsNgModuleLoader(this._Compiler_54,this.parent.get(import68.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_84;
  }
  get _ROUTES_85():any[] {
      if ((this.__ROUTES_85 == null)) { (this.__ROUTES_85 = [[
        {
          path: '',
          redirectTo: '/messages',
          pathMatch: 'full'
        }
        ,
        {
          path: 'messages',
          component: import89.MessagesComponent
        }
        ,
        {
          path: 'auth',
          component: import90.AuthenticationComponent,
          loadChildren: './auth/auth.module#AuthModule'
        }

      ]
    ]); }
    return this.__ROUTES_85;
  }
  get _Router_86():any {
    if ((this.__Router_86 == null)) { (this.__Router_86 = import22.setupRouter(this._ApplicationRef_53,this._UrlSerializer_82,this._RouterOutletMap_83,this._Location_81,this,this._NgModuleFactoryLoader_84,this._Compiler_54,this._ROUTES_85,this._ROUTER_CONFIGURATION_79,this.parent.get(import91.UrlHandlingStrategy,(null as any)))); }
    return this.__Router_86;
  }
  get _ActivatedRoute_87():any {
    if ((this.__ActivatedRoute_87 == null)) { (this.__ActivatedRoute_87 = import22.rootRoute(this._Router_86)); }
    return this.__ActivatedRoute_87;
  }
  get _PreloadAllModules_91():import69.PreloadAllModules {
    if ((this.__PreloadAllModules_91 == null)) { (this.__PreloadAllModules_91 = new import69.PreloadAllModules()); }
    return this.__PreloadAllModules_91;
  }
  get _ROUTER_INITIALIZER_92():any {
    if ((this.__ROUTER_INITIALIZER_92 == null)) { (this.__ROUTER_INITIALIZER_92 = import22.initialRouterNavigation(this._Router_86,this._ApplicationRef_53,this._RouterPreloader_90,this._ROUTER_CONFIGURATION_79)); }
    return this.__ROUTER_INITIALIZER_92;
  }
  get _APP_BOOTSTRAP_LISTENER_93():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_93 == null)) { (this.__APP_BOOTSTRAP_LISTENER_93 = [this._ROUTER_INITIALIZER_92]); }
    return this.__APP_BOOTSTRAP_LISTENER_93;
  }
  get _AuthService_94():import70.AuthService {
    if ((this.__AuthService_94 == null)) { (this.__AuthService_94 = new import70.AuthService(this._Http_76,this._ErrorService_77)); }
    return this.__AuthService_94;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._NgbAlertModule_1 = new import3.NgbAlertModule();
    this._NgbButtonsModule_2 = new import4.NgbButtonsModule();
    this._NgbCollapseModule_3 = new import5.NgbCollapseModule();
    this._NgbProgressbarModule_4 = new import6.NgbProgressbarModule();
    this._NgbTooltipModule_5 = new import7.NgbTooltipModule();
    this._NgbTypeaheadModule_6 = new import8.NgbTypeaheadModule();
    this._NgbAccordionModule_7 = new import9.NgbAccordionModule();
    this._NgbCarouselModule_8 = new import10.NgbCarouselModule();
    this._InternalFormsSharedModule_9 = new import11.InternalFormsSharedModule();
    this._FormsModule_10 = new import12.FormsModule();
    this._NgbDatepickerModule_11 = new import13.NgbDatepickerModule();
    this._NgbDropdownModule_12 = new import14.NgbDropdownModule();
    this._NgbModalModule_13 = new import15.NgbModalModule();
    this._NgbPaginationModule_14 = new import16.NgbPaginationModule();
    this._NgbPopoverModule_15 = new import17.NgbPopoverModule();
    this._NgbRatingModule_16 = new import18.NgbRatingModule();
    this._NgbTabsetModule_17 = new import19.NgbTabsetModule();
    this._NgbTimepickerModule_18 = new import20.NgbTimepickerModule();
    this._NgbRootModule_19 = new import21.NgbRootModule();
    this._ROUTER_FORROOT_GUARD_20 = import22.provideForRootGuard(this.parent.get(import92.Router,(null as any)));
    this._RouterModule_21 = new import22.RouterModule(this._ROUTER_FORROOT_GUARD_20);
    this._ApplicationModule_22 = new import23.ApplicationModule();
    this._BrowserModule_23 = new import24.BrowserModule(this.parent.get(import24.BrowserModule,(null as any)));
    this._HttpModule_24 = new import25.HttpModule();
    this._MessageModule_25 = new import26.MessageModule();
    this._AppModule_26 = new import1.AppModule();
    this._ErrorHandler_49 = import24.errorHandler();
    this._ApplicationInitStatus_50 = new import48.ApplicationInitStatus(this.parent.get(import48.APP_INITIALIZER,(null as any)));
    this._Testability_51 = new import49.Testability(this.parent.get(import85.NgZone));
    this._ApplicationRef__52 = new import50.ApplicationRef_(this.parent.get(import85.NgZone),this.parent.get(import93.Console),this,this._ErrorHandler_49,this,this._ApplicationInitStatus_50,this.parent.get(import49.TestabilityRegistry,(null as any)),this._Testability_51);
    this._NoPreloading_88 = new import69.NoPreloading();
    this._PreloadingStrategy_89 = this._NoPreloading_88;
    this._RouterPreloader_90 = new import69.RouterPreloader(this._Router_86,this._NgModuleFactoryLoader_84,this._Compiler_54,this,this._PreloadingStrategy_89);
    return this._AppModule_26;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.NgbAlertModule)) { return this._NgbAlertModule_1; }
    if ((token === import4.NgbButtonsModule)) { return this._NgbButtonsModule_2; }
    if ((token === import5.NgbCollapseModule)) { return this._NgbCollapseModule_3; }
    if ((token === import6.NgbProgressbarModule)) { return this._NgbProgressbarModule_4; }
    if ((token === import7.NgbTooltipModule)) { return this._NgbTooltipModule_5; }
    if ((token === import8.NgbTypeaheadModule)) { return this._NgbTypeaheadModule_6; }
    if ((token === import9.NgbAccordionModule)) { return this._NgbAccordionModule_7; }
    if ((token === import10.NgbCarouselModule)) { return this._NgbCarouselModule_8; }
    if ((token === import11.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_9; }
    if ((token === import12.FormsModule)) { return this._FormsModule_10; }
    if ((token === import13.NgbDatepickerModule)) { return this._NgbDatepickerModule_11; }
    if ((token === import14.NgbDropdownModule)) { return this._NgbDropdownModule_12; }
    if ((token === import15.NgbModalModule)) { return this._NgbModalModule_13; }
    if ((token === import16.NgbPaginationModule)) { return this._NgbPaginationModule_14; }
    if ((token === import17.NgbPopoverModule)) { return this._NgbPopoverModule_15; }
    if ((token === import18.NgbRatingModule)) { return this._NgbRatingModule_16; }
    if ((token === import19.NgbTabsetModule)) { return this._NgbTabsetModule_17; }
    if ((token === import20.NgbTimepickerModule)) { return this._NgbTimepickerModule_18; }
    if ((token === import21.NgbRootModule)) { return this._NgbRootModule_19; }
    if ((token === import22.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_20; }
    if ((token === import22.RouterModule)) { return this._RouterModule_21; }
    if ((token === import23.ApplicationModule)) { return this._ApplicationModule_22; }
    if ((token === import24.BrowserModule)) { return this._BrowserModule_23; }
    if ((token === import25.HttpModule)) { return this._HttpModule_24; }
    if ((token === import26.MessageModule)) { return this._MessageModule_25; }
    if ((token === import1.AppModule)) { return this._AppModule_26; }
    if ((token === import94.LOCALE_ID)) { return this._LOCALE_ID_27; }
    if ((token === import27.NgLocalization)) { return this._NgLocalization_28; }
    if ((token === import28.RadioControlRegistry)) { return this._RadioControlRegistry_29; }
    if ((token === import29.NgbModalStack)) { return this._NgbModalStack_30; }
    if ((token === import30.NgbModal)) { return this._NgbModal_31; }
    if ((token === import31.NgbAlertConfig)) { return this._NgbAlertConfig_32; }
    if ((token === import32.NgbProgressbarConfig)) { return this._NgbProgressbarConfig_33; }
    if ((token === import33.NgbTooltipConfig)) { return this._NgbTooltipConfig_34; }
    if ((token === import34.NgbTypeaheadConfig)) { return this._NgbTypeaheadConfig_35; }
    if ((token === import35.NgbAccordionConfig)) { return this._NgbAccordionConfig_36; }
    if ((token === import36.NgbCarouselConfig)) { return this._NgbCarouselConfig_37; }
    if ((token === import37.NgbCalendar)) { return this._NgbCalendar_38; }
    if ((token === import38.NgbDatepickerI18n)) { return this._NgbDatepickerI18n_39; }
    if ((token === import39.NgbDateParserFormatter)) { return this._NgbDateParserFormatter_40; }
    if ((token === import40.NgbDatepickerService)) { return this._NgbDatepickerService_41; }
    if ((token === import41.NgbDatepickerConfig)) { return this._NgbDatepickerConfig_42; }
    if ((token === import42.NgbDropdownConfig)) { return this._NgbDropdownConfig_43; }
    if ((token === import43.NgbPaginationConfig)) { return this._NgbPaginationConfig_44; }
    if ((token === import44.NgbPopoverConfig)) { return this._NgbPopoverConfig_45; }
    if ((token === import45.NgbRatingConfig)) { return this._NgbRatingConfig_46; }
    if ((token === import46.NgbTabsetConfig)) { return this._NgbTabsetConfig_47; }
    if ((token === import47.NgbTimepickerConfig)) { return this._NgbTimepickerConfig_48; }
    if ((token === import95.ErrorHandler)) { return this._ErrorHandler_49; }
    if ((token === import48.ApplicationInitStatus)) { return this._ApplicationInitStatus_50; }
    if ((token === import49.Testability)) { return this._Testability_51; }
    if ((token === import50.ApplicationRef_)) { return this._ApplicationRef__52; }
    if ((token === import50.ApplicationRef)) { return this._ApplicationRef_53; }
    if ((token === import51.Compiler)) { return this._Compiler_54; }
    if ((token === import82.APP_ID)) { return this._APP_ID_55; }
    if ((token === import96.DOCUMENT)) { return this._DOCUMENT_56; }
    if ((token === import52.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_57; }
    if ((token === import53.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_58; }
    if ((token === import53.EventManager)) { return this._EventManager_59; }
    if ((token === import54.DomSharedStylesHost)) { return this._DomSharedStylesHost_60; }
    if ((token === import97.AnimationDriver)) { return this._AnimationDriver_61; }
    if ((token === import55.DomRootRenderer)) { return this._DomRootRenderer_62; }
    if ((token === import98.RootRenderer)) { return this._RootRenderer_63; }
    if ((token === import56.DomSanitizer)) { return this._DomSanitizer_64; }
    if ((token === import99.Sanitizer)) { return this._Sanitizer_65; }
    if ((token === import57.ViewUtils)) { return this._ViewUtils_66; }
    if ((token === import100.IterableDiffers)) { return this._IterableDiffers_67; }
    if ((token === import101.KeyValueDiffers)) { return this._KeyValueDiffers_68; }
    if ((token === import54.SharedStylesHost)) { return this._SharedStylesHost_69; }
    if ((token === import58.Title)) { return this._Title_70; }
    if ((token === import59.BrowserXhr)) { return this._BrowserXhr_71; }
    if ((token === import60.ResponseOptions)) { return this._ResponseOptions_72; }
    if ((token === import102.XSRFStrategy)) { return this._XSRFStrategy_73; }
    if ((token === import61.XHRBackend)) { return this._XHRBackend_74; }
    if ((token === import62.RequestOptions)) { return this._RequestOptions_75; }
    if ((token === import103.Http)) { return this._Http_76; }
    if ((token === import63.ErrorService)) { return this._ErrorService_77; }
    if ((token === import64.MessageService)) { return this._MessageService_78; }
    if ((token === import22.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_79; }
    if ((token === import88.LocationStrategy)) { return this._LocationStrategy_80; }
    if ((token === import65.Location)) { return this._Location_81; }
    if ((token === import66.UrlSerializer)) { return this._UrlSerializer_82; }
    if ((token === import67.RouterOutletMap)) { return this._RouterOutletMap_83; }
    if ((token === import104.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_84; }
    if ((token === import105.ROUTES)) { return this._ROUTES_85; }
    if ((token === import92.Router)) { return this._Router_86; }
    if ((token === import106.ActivatedRoute)) { return this._ActivatedRoute_87; }
    if ((token === import69.NoPreloading)) { return this._NoPreloading_88; }
    if ((token === import69.PreloadingStrategy)) { return this._PreloadingStrategy_89; }
    if ((token === import69.RouterPreloader)) { return this._RouterPreloader_90; }
    if ((token === import69.PreloadAllModules)) { return this._PreloadAllModules_91; }
    if ((token === import22.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_92; }
    if ((token === import82.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_93; }
    if ((token === import70.AuthService)) { return this._AuthService_94; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__52.ngOnDestroy();
    this._RouterPreloader_90.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);