/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@ng-bootstrap/ng-bootstrap/alert/alert.module';
import * as import4 from '@ng-bootstrap/ng-bootstrap/buttons/radio.module';
import * as import5 from '@ng-bootstrap/ng-bootstrap/collapse/collapse.module';
import * as import6 from '@ng-bootstrap/ng-bootstrap/progressbar/progressbar.module';
import * as import7 from '@ng-bootstrap/ng-bootstrap/tooltip/tooltip.module';
import * as import8 from '@ng-bootstrap/ng-bootstrap/typeahead/typeahead.module';
import * as import9 from '@ng-bootstrap/ng-bootstrap/accordion/accordion.module';
import * as import10 from '@ng-bootstrap/ng-bootstrap/carousel/carousel.module';
import * as import11 from '@angular/forms/src/directives';
import * as import12 from '@angular/forms/src/form_providers';
import * as import13 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker.module';
import * as import14 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown.module';
import * as import15 from '@ng-bootstrap/ng-bootstrap/modal/modal.module';
import * as import16 from '@ng-bootstrap/ng-bootstrap/pagination/pagination.module';
import * as import17 from '@ng-bootstrap/ng-bootstrap/popover/popover.module';
import * as import18 from '@ng-bootstrap/ng-bootstrap/rating/rating.module';
import * as import19 from '@ng-bootstrap/ng-bootstrap/tabset/tabset.module';
import * as import20 from '@ng-bootstrap/ng-bootstrap/timepicker/timepicker.module';
import * as import21 from '@ng-bootstrap/ng-bootstrap/index';
import * as import22 from '@angular/router/src/router_module';
import * as import23 from 'ng2-file-upload/file-upload/file-upload.module';
import * as import24 from './upload/upload.module';
import * as import25 from '@angular/core/src/application_module';
import * as import26 from '@angular/platform-browser/src/browser';
import * as import27 from '@angular/http/src/http_module';
import * as import28 from '@angular/common/src/localization';
import * as import29 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import30 from '@ng-bootstrap/ng-bootstrap/modal/modal-stack';
import * as import31 from '@ng-bootstrap/ng-bootstrap/modal/modal';
import * as import32 from '@ng-bootstrap/ng-bootstrap/alert/alert-config';
import * as import33 from '@ng-bootstrap/ng-bootstrap/progressbar/progressbar-config';
import * as import34 from '@ng-bootstrap/ng-bootstrap/tooltip/tooltip-config';
import * as import35 from '@ng-bootstrap/ng-bootstrap/typeahead/typeahead-config';
import * as import36 from '@ng-bootstrap/ng-bootstrap/accordion/accordion-config';
import * as import37 from '@ng-bootstrap/ng-bootstrap/carousel/carousel-config';
import * as import38 from '@ng-bootstrap/ng-bootstrap/datepicker/ngb-calendar';
import * as import39 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker-i18n';
import * as import40 from '@ng-bootstrap/ng-bootstrap/datepicker/ngb-date-parser-formatter';
import * as import41 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker-service';
import * as import42 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker-config';
import * as import43 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown-config';
import * as import44 from '@ng-bootstrap/ng-bootstrap/pagination/pagination-config';
import * as import45 from '@ng-bootstrap/ng-bootstrap/popover/popover-config';
import * as import46 from '@ng-bootstrap/ng-bootstrap/rating/rating-config';
import * as import47 from '@ng-bootstrap/ng-bootstrap/tabset/tabset-config';
import * as import48 from '@ng-bootstrap/ng-bootstrap/timepicker/timepicker-config';
import * as import49 from '@angular/core/src/application_init';
import * as import50 from '@angular/core/src/testability/testability';
import * as import51 from '@angular/core/src/application_ref';
import * as import52 from '@angular/core/src/linker/compiler';
import * as import53 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import54 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import55 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import56 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import57 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import58 from '@angular/core/src/linker/view_utils';
import * as import59 from '@angular/platform-browser/src/browser/title';
import * as import60 from '@angular/http/src/backends/browser_xhr';
import * as import61 from '@angular/http/src/base_response_options';
import * as import62 from '@angular/http/src/backends/xhr_backend';
import * as import63 from '@angular/http/src/base_request_options';
import * as import64 from '@angular/common/src/location/location';
import * as import65 from '@angular/router/src/url_tree';
import * as import66 from '@angular/router/src/router_outlet_map';
import * as import67 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import68 from '@angular/router/src/router_preloader';
import * as import69 from './errors/error.service';
import * as import70 from './auth/auth.service';
import * as import71 from './news/news.service';
import * as import72 from './profile/profile.service';
import * as import73 from '@angular/core/src/di/injector';
import * as import74 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory';
import * as import75 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/tooltip/tooltip.ngfactory';
import * as import76 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead-window.ngfactory';
import * as import77 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.ngfactory';
import * as import78 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-backdrop.ngfactory';
import * as import79 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-window.ngfactory';
import * as import80 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/popover/popover.ngfactory';
import * as import81 from './news/news.component.ngfactory';
import * as import82 from './profile/profile.component.ngfactory';
import * as import83 from './games/games.component.ngfactory';
import * as import84 from './upload/upload.component.ngfactory';
import * as import85 from './auth/authentication.component.ngfactory';
import * as import86 from './app.component.ngfactory';
import * as import87 from '@angular/core/src/application_tokens';
import * as import88 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import89 from '@angular/platform-browser/src/dom/events/key_events';
import * as import90 from '@angular/core/src/zone/ng_zone';
import * as import91 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import92 from '@angular/common/src/location/platform_location';
import * as import93 from '@angular/common/src/location/location_strategy';
import * as import94 from './news/news.component';
import * as import95 from './profile/profile.component';
import * as import96 from './games/games.component';
import * as import97 from './upload/upload.component';
import * as import98 from './auth/authentication.component';
import * as import99 from '@angular/router/src/url_handling_strategy';
import * as import100 from '@angular/router/src/router';
import * as import101 from '@angular/core/src/console';
import * as import102 from '@angular/core/src/i18n/tokens';
import * as import103 from '@angular/core/src/error_handler';
import * as import104 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import105 from '@angular/platform-browser/src/dom/animation_driver';
import * as import106 from '@angular/core/src/render/api';
import * as import107 from '@angular/core/src/security';
import * as import108 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import109 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import110 from '@angular/http/src/interfaces';
import * as import111 from '@angular/http/src/http';
import * as import112 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import113 from '@angular/router/src/router_config_loader';
import * as import114 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _NgbAlertModule_1:import3.NgbAlertModule;
  _NgbButtonsModule_2:import4.NgbButtonsModule;
  _NgbCollapseModule_3:import5.NgbCollapseModule;
  _NgbProgressbarModule_4:import6.NgbProgressbarModule;
  _NgbTooltipModule_5:import7.NgbTooltipModule;
  _NgbTypeaheadModule_6:import8.NgbTypeaheadModule;
  _NgbAccordionModule_7:import9.NgbAccordionModule;
  _NgbCarouselModule_8:import10.NgbCarouselModule;
  _InternalFormsSharedModule_9:import11.InternalFormsSharedModule;
  _FormsModule_10:import12.FormsModule;
  _NgbDatepickerModule_11:import13.NgbDatepickerModule;
  _NgbDropdownModule_12:import14.NgbDropdownModule;
  _NgbModalModule_13:import15.NgbModalModule;
  _NgbPaginationModule_14:import16.NgbPaginationModule;
  _NgbPopoverModule_15:import17.NgbPopoverModule;
  _NgbRatingModule_16:import18.NgbRatingModule;
  _NgbTabsetModule_17:import19.NgbTabsetModule;
  _NgbTimepickerModule_18:import20.NgbTimepickerModule;
  _NgbRootModule_19:import21.NgbRootModule;
  _ROUTER_FORROOT_GUARD_20:any;
  _RouterModule_21:import22.RouterModule;
  _FileUploadModule_22:import23.FileUploadModule;
  _UploadModule_23:import24.UploadModule;
  _ApplicationModule_24:import25.ApplicationModule;
  _BrowserModule_25:import26.BrowserModule;
  _HttpModule_26:import27.HttpModule;
  _AppModule_27:import1.AppModule;
  __LOCALE_ID_28:any;
  __NgLocalization_29:import28.NgLocaleLocalization;
  __RadioControlRegistry_30:import29.RadioControlRegistry;
  __NgbModalStack_31:import30.NgbModalStack;
  __NgbModal_32:import31.NgbModal;
  __NgbAlertConfig_33:import32.NgbAlertConfig;
  __NgbProgressbarConfig_34:import33.NgbProgressbarConfig;
  __NgbTooltipConfig_35:import34.NgbTooltipConfig;
  __NgbTypeaheadConfig_36:import35.NgbTypeaheadConfig;
  __NgbAccordionConfig_37:import36.NgbAccordionConfig;
  __NgbCarouselConfig_38:import37.NgbCarouselConfig;
  __NgbCalendar_39:import38.NgbCalendarGregorian;
  __NgbDatepickerI18n_40:import39.NgbDatepickerI18nDefault;
  __NgbDateParserFormatter_41:import40.NgbDateISOParserFormatter;
  __NgbDatepickerService_42:import41.NgbDatepickerService;
  __NgbDatepickerConfig_43:import42.NgbDatepickerConfig;
  __NgbDropdownConfig_44:import43.NgbDropdownConfig;
  __NgbPaginationConfig_45:import44.NgbPaginationConfig;
  __NgbPopoverConfig_46:import45.NgbPopoverConfig;
  __NgbRatingConfig_47:import46.NgbRatingConfig;
  __NgbTabsetConfig_48:import47.NgbTabsetConfig;
  __NgbTimepickerConfig_49:import48.NgbTimepickerConfig;
  _ErrorHandler_50:any;
  _ApplicationInitStatus_51:import49.ApplicationInitStatus;
  _Testability_52:import50.Testability;
  _ApplicationRef__53:import51.ApplicationRef_;
  __ApplicationRef_54:any;
  __Compiler_55:import52.Compiler;
  __APP_ID_56:any;
  __DOCUMENT_57:any;
  __HAMMER_GESTURE_CONFIG_58:import53.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_59:any[];
  __EventManager_60:import54.EventManager;
  __DomSharedStylesHost_61:import55.DomSharedStylesHost;
  __AnimationDriver_62:any;
  __DomRootRenderer_63:import56.DomRootRenderer_;
  __RootRenderer_64:any;
  __DomSanitizer_65:import57.DomSanitizerImpl;
  __Sanitizer_66:any;
  __ViewUtils_67:import58.ViewUtils;
  __IterableDiffers_68:any;
  __KeyValueDiffers_69:any;
  __SharedStylesHost_70:any;
  __Title_71:import59.Title;
  __BrowserXhr_72:import60.BrowserXhr;
  __ResponseOptions_73:import61.BaseResponseOptions;
  __XSRFStrategy_74:any;
  __XHRBackend_75:import62.XHRBackend;
  __RequestOptions_76:import63.BaseRequestOptions;
  __Http_77:any;
  __ROUTER_CONFIGURATION_78:any;
  __LocationStrategy_79:any;
  __Location_80:import64.Location;
  __UrlSerializer_81:import65.DefaultUrlSerializer;
  __RouterOutletMap_82:import66.RouterOutletMap;
  __NgModuleFactoryLoader_83:import67.SystemJsNgModuleLoader;
  __ROUTES_84:any[];
  __Router_85:any;
  __ActivatedRoute_86:any;
  _NoPreloading_87:import68.NoPreloading;
  _PreloadingStrategy_88:any;
  _RouterPreloader_89:import68.RouterPreloader;
  __PreloadAllModules_90:import68.PreloadAllModules;
  __ROUTER_INITIALIZER_91:any;
  __APP_BOOTSTRAP_LISTENER_92:any[];
  __ErrorService_93:import69.ErrorService;
  __AuthService_94:import70.AuthService;
  __NewsService_95:import71.NewsService;
  __ProfileService_96:import72.ProfileService;
  constructor(parent:import73.Injector) {
    super(parent,[
      import74.NgbAlertNgFactory,
      import75.NgbTooltipWindowNgFactory,
      import76.NgbTypeaheadWindowNgFactory,
      import77.NgbDatepickerNgFactory,
      import78.NgbModalBackdropNgFactory,
      import79.NgbModalWindowNgFactory,
      import80.NgbPopoverWindowNgFactory,
      import81.NewsComponentNgFactory,
      import82.ProfileComponentNgFactory,
      import83.GamesComponentNgFactory,
      import84.UploadComponentNgFactory,
      import85.AuthenticationComponentNgFactory,
      import86.AppComponentNgFactory
    ]
    ,[import86.AppComponentNgFactory]);
  }
  get _LOCALE_ID_28():any {
    if ((this.__LOCALE_ID_28 == null)) { (this.__LOCALE_ID_28 = 'en-US'); }
    return this.__LOCALE_ID_28;
  }
  get _NgLocalization_29():import28.NgLocaleLocalization {
    if ((this.__NgLocalization_29 == null)) { (this.__NgLocalization_29 = new import28.NgLocaleLocalization(this._LOCALE_ID_28)); }
    return this.__NgLocalization_29;
  }
  get _RadioControlRegistry_30():import29.RadioControlRegistry {
    if ((this.__RadioControlRegistry_30 == null)) { (this.__RadioControlRegistry_30 = new import29.RadioControlRegistry()); }
    return this.__RadioControlRegistry_30;
  }
  get _NgbModalStack_31():import30.NgbModalStack {
    if ((this.__NgbModalStack_31 == null)) { (this.__NgbModalStack_31 = new import30.NgbModalStack()); }
    return this.__NgbModalStack_31;
  }
  get _NgbModal_32():import31.NgbModal {
    if ((this.__NgbModal_32 == null)) { (this.__NgbModal_32 = new import31.NgbModal(this,this,this._NgbModalStack_31)); }
    return this.__NgbModal_32;
  }
  get _NgbAlertConfig_33():import32.NgbAlertConfig {
    if ((this.__NgbAlertConfig_33 == null)) { (this.__NgbAlertConfig_33 = new import32.NgbAlertConfig()); }
    return this.__NgbAlertConfig_33;
  }
  get _NgbProgressbarConfig_34():import33.NgbProgressbarConfig {
    if ((this.__NgbProgressbarConfig_34 == null)) { (this.__NgbProgressbarConfig_34 = new import33.NgbProgressbarConfig()); }
    return this.__NgbProgressbarConfig_34;
  }
  get _NgbTooltipConfig_35():import34.NgbTooltipConfig {
    if ((this.__NgbTooltipConfig_35 == null)) { (this.__NgbTooltipConfig_35 = new import34.NgbTooltipConfig()); }
    return this.__NgbTooltipConfig_35;
  }
  get _NgbTypeaheadConfig_36():import35.NgbTypeaheadConfig {
    if ((this.__NgbTypeaheadConfig_36 == null)) { (this.__NgbTypeaheadConfig_36 = new import35.NgbTypeaheadConfig()); }
    return this.__NgbTypeaheadConfig_36;
  }
  get _NgbAccordionConfig_37():import36.NgbAccordionConfig {
    if ((this.__NgbAccordionConfig_37 == null)) { (this.__NgbAccordionConfig_37 = new import36.NgbAccordionConfig()); }
    return this.__NgbAccordionConfig_37;
  }
  get _NgbCarouselConfig_38():import37.NgbCarouselConfig {
    if ((this.__NgbCarouselConfig_38 == null)) { (this.__NgbCarouselConfig_38 = new import37.NgbCarouselConfig()); }
    return this.__NgbCarouselConfig_38;
  }
  get _NgbCalendar_39():import38.NgbCalendarGregorian {
    if ((this.__NgbCalendar_39 == null)) { (this.__NgbCalendar_39 = new import38.NgbCalendarGregorian()); }
    return this.__NgbCalendar_39;
  }
  get _NgbDatepickerI18n_40():import39.NgbDatepickerI18nDefault {
    if ((this.__NgbDatepickerI18n_40 == null)) { (this.__NgbDatepickerI18n_40 = new import39.NgbDatepickerI18nDefault()); }
    return this.__NgbDatepickerI18n_40;
  }
  get _NgbDateParserFormatter_41():import40.NgbDateISOParserFormatter {
    if ((this.__NgbDateParserFormatter_41 == null)) { (this.__NgbDateParserFormatter_41 = new import40.NgbDateISOParserFormatter()); }
    return this.__NgbDateParserFormatter_41;
  }
  get _NgbDatepickerService_42():import41.NgbDatepickerService {
    if ((this.__NgbDatepickerService_42 == null)) { (this.__NgbDatepickerService_42 = new import41.NgbDatepickerService(this._NgbCalendar_39)); }
    return this.__NgbDatepickerService_42;
  }
  get _NgbDatepickerConfig_43():import42.NgbDatepickerConfig {
    if ((this.__NgbDatepickerConfig_43 == null)) { (this.__NgbDatepickerConfig_43 = new import42.NgbDatepickerConfig()); }
    return this.__NgbDatepickerConfig_43;
  }
  get _NgbDropdownConfig_44():import43.NgbDropdownConfig {
    if ((this.__NgbDropdownConfig_44 == null)) { (this.__NgbDropdownConfig_44 = new import43.NgbDropdownConfig()); }
    return this.__NgbDropdownConfig_44;
  }
  get _NgbPaginationConfig_45():import44.NgbPaginationConfig {
    if ((this.__NgbPaginationConfig_45 == null)) { (this.__NgbPaginationConfig_45 = new import44.NgbPaginationConfig()); }
    return this.__NgbPaginationConfig_45;
  }
  get _NgbPopoverConfig_46():import45.NgbPopoverConfig {
    if ((this.__NgbPopoverConfig_46 == null)) { (this.__NgbPopoverConfig_46 = new import45.NgbPopoverConfig()); }
    return this.__NgbPopoverConfig_46;
  }
  get _NgbRatingConfig_47():import46.NgbRatingConfig {
    if ((this.__NgbRatingConfig_47 == null)) { (this.__NgbRatingConfig_47 = new import46.NgbRatingConfig()); }
    return this.__NgbRatingConfig_47;
  }
  get _NgbTabsetConfig_48():import47.NgbTabsetConfig {
    if ((this.__NgbTabsetConfig_48 == null)) { (this.__NgbTabsetConfig_48 = new import47.NgbTabsetConfig()); }
    return this.__NgbTabsetConfig_48;
  }
  get _NgbTimepickerConfig_49():import48.NgbTimepickerConfig {
    if ((this.__NgbTimepickerConfig_49 == null)) { (this.__NgbTimepickerConfig_49 = new import48.NgbTimepickerConfig()); }
    return this.__NgbTimepickerConfig_49;
  }
  get _ApplicationRef_54():any {
    if ((this.__ApplicationRef_54 == null)) { (this.__ApplicationRef_54 = this._ApplicationRef__53); }
    return this.__ApplicationRef_54;
  }
  get _Compiler_55():import52.Compiler {
    if ((this.__Compiler_55 == null)) { (this.__Compiler_55 = new import52.Compiler()); }
    return this.__Compiler_55;
  }
  get _APP_ID_56():any {
    if ((this.__APP_ID_56 == null)) { (this.__APP_ID_56 = import87._appIdRandomProviderFactory()); }
    return this.__APP_ID_56;
  }
  get _DOCUMENT_57():any {
    if ((this.__DOCUMENT_57 == null)) { (this.__DOCUMENT_57 = import26._document()); }
    return this.__DOCUMENT_57;
  }
  get _HAMMER_GESTURE_CONFIG_58():import53.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_58 == null)) { (this.__HAMMER_GESTURE_CONFIG_58 = new import53.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_58;
  }
  get _EVENT_MANAGER_PLUGINS_59():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_59 == null)) { (this.__EVENT_MANAGER_PLUGINS_59 = [
      new import88.DomEventsPlugin(),
      new import89.KeyEventsPlugin(),
      new import53.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_58)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_59;
  }
  get _EventManager_60():import54.EventManager {
    if ((this.__EventManager_60 == null)) { (this.__EventManager_60 = new import54.EventManager(this._EVENT_MANAGER_PLUGINS_59,this.parent.get(import90.NgZone))); }
    return this.__EventManager_60;
  }
  get _DomSharedStylesHost_61():import55.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_61 == null)) { (this.__DomSharedStylesHost_61 = new import55.DomSharedStylesHost(this._DOCUMENT_57)); }
    return this.__DomSharedStylesHost_61;
  }
  get _AnimationDriver_62():any {
    if ((this.__AnimationDriver_62 == null)) { (this.__AnimationDriver_62 = import26._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_62;
  }
  get _DomRootRenderer_63():import56.DomRootRenderer_ {
    if ((this.__DomRootRenderer_63 == null)) { (this.__DomRootRenderer_63 = new import56.DomRootRenderer_(this._DOCUMENT_57,this._EventManager_60,this._DomSharedStylesHost_61,this._AnimationDriver_62,this._APP_ID_56)); }
    return this.__DomRootRenderer_63;
  }
  get _RootRenderer_64():any {
    if ((this.__RootRenderer_64 == null)) { (this.__RootRenderer_64 = import91._createConditionalRootRenderer(this._DomRootRenderer_63,this.parent.get(import91.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_64;
  }
  get _DomSanitizer_65():import57.DomSanitizerImpl {
    if ((this.__DomSanitizer_65 == null)) { (this.__DomSanitizer_65 = new import57.DomSanitizerImpl()); }
    return this.__DomSanitizer_65;
  }
  get _Sanitizer_66():any {
    if ((this.__Sanitizer_66 == null)) { (this.__Sanitizer_66 = this._DomSanitizer_65); }
    return this.__Sanitizer_66;
  }
  get _ViewUtils_67():import58.ViewUtils {
    if ((this.__ViewUtils_67 == null)) { (this.__ViewUtils_67 = new import58.ViewUtils(this._RootRenderer_64,this._Sanitizer_66)); }
    return this.__ViewUtils_67;
  }
  get _IterableDiffers_68():any {
    if ((this.__IterableDiffers_68 == null)) { (this.__IterableDiffers_68 = import25._iterableDiffersFactory()); }
    return this.__IterableDiffers_68;
  }
  get _KeyValueDiffers_69():any {
    if ((this.__KeyValueDiffers_69 == null)) { (this.__KeyValueDiffers_69 = import25._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_69;
  }
  get _SharedStylesHost_70():any {
    if ((this.__SharedStylesHost_70 == null)) { (this.__SharedStylesHost_70 = this._DomSharedStylesHost_61); }
    return this.__SharedStylesHost_70;
  }
  get _Title_71():import59.Title {
    if ((this.__Title_71 == null)) { (this.__Title_71 = new import59.Title()); }
    return this.__Title_71;
  }
  get _BrowserXhr_72():import60.BrowserXhr {
    if ((this.__BrowserXhr_72 == null)) { (this.__BrowserXhr_72 = new import60.BrowserXhr()); }
    return this.__BrowserXhr_72;
  }
  get _ResponseOptions_73():import61.BaseResponseOptions {
    if ((this.__ResponseOptions_73 == null)) { (this.__ResponseOptions_73 = new import61.BaseResponseOptions()); }
    return this.__ResponseOptions_73;
  }
  get _XSRFStrategy_74():any {
    if ((this.__XSRFStrategy_74 == null)) { (this.__XSRFStrategy_74 = import27._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_74;
  }
  get _XHRBackend_75():import62.XHRBackend {
    if ((this.__XHRBackend_75 == null)) { (this.__XHRBackend_75 = new import62.XHRBackend(this._BrowserXhr_72,this._ResponseOptions_73,this._XSRFStrategy_74)); }
    return this.__XHRBackend_75;
  }
  get _RequestOptions_76():import63.BaseRequestOptions {
    if ((this.__RequestOptions_76 == null)) { (this.__RequestOptions_76 = new import63.BaseRequestOptions()); }
    return this.__RequestOptions_76;
  }
  get _Http_77():any {
    if ((this.__Http_77 == null)) { (this.__Http_77 = import27.httpFactory(this._XHRBackend_75,this._RequestOptions_76)); }
    return this.__Http_77;
  }
  get _ROUTER_CONFIGURATION_78():any {
    if ((this.__ROUTER_CONFIGURATION_78 == null)) { (this.__ROUTER_CONFIGURATION_78 = {}); }
    return this.__ROUTER_CONFIGURATION_78;
  }
  get _LocationStrategy_79():any {
    if ((this.__LocationStrategy_79 == null)) { (this.__LocationStrategy_79 = import22.provideLocationStrategy(this.parent.get(import92.PlatformLocation),this.parent.get(import93.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_78)); }
    return this.__LocationStrategy_79;
  }
  get _Location_80():import64.Location {
    if ((this.__Location_80 == null)) { (this.__Location_80 = new import64.Location(this._LocationStrategy_79)); }
    return this.__Location_80;
  }
  get _UrlSerializer_81():import65.DefaultUrlSerializer {
    if ((this.__UrlSerializer_81 == null)) { (this.__UrlSerializer_81 = new import65.DefaultUrlSerializer()); }
    return this.__UrlSerializer_81;
  }
  get _RouterOutletMap_82():import66.RouterOutletMap {
    if ((this.__RouterOutletMap_82 == null)) { (this.__RouterOutletMap_82 = new import66.RouterOutletMap()); }
    return this.__RouterOutletMap_82;
  }
  get _NgModuleFactoryLoader_83():import67.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_83 == null)) { (this.__NgModuleFactoryLoader_83 = new import67.SystemJsNgModuleLoader(this._Compiler_55,this.parent.get(import67.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_83;
  }
  get _ROUTES_84():any[] {
      if ((this.__ROUTES_84 == null)) { (this.__ROUTES_84 = [[
        {
          path: '',
          redirectTo: '/news',
          pathMatch: 'full'
        }
        ,
        {
          path: 'news',
          component: import94.NewsComponent
        }
        ,
        {
          path: 'profile',
          component: import95.ProfileComponent
        }
        ,
        {
          path: 'games',
          component: import96.GamesComponent
        }
        ,
        {
          path: 'upload',
          component: import97.UploadComponent
        }
        ,
        {
          path: 'auth',
          component: import98.AuthenticationComponent,
          loadChildren: './auth/auth.module#AuthModule'
        }

      ]
    ]); }
    return this.__ROUTES_84;
  }
  get _Router_85():any {
    if ((this.__Router_85 == null)) { (this.__Router_85 = import22.setupRouter(this._ApplicationRef_54,this._UrlSerializer_81,this._RouterOutletMap_82,this._Location_80,this,this._NgModuleFactoryLoader_83,this._Compiler_55,this._ROUTES_84,this._ROUTER_CONFIGURATION_78,this.parent.get(import99.UrlHandlingStrategy,(null as any)))); }
    return this.__Router_85;
  }
  get _ActivatedRoute_86():any {
    if ((this.__ActivatedRoute_86 == null)) { (this.__ActivatedRoute_86 = import22.rootRoute(this._Router_85)); }
    return this.__ActivatedRoute_86;
  }
  get _PreloadAllModules_90():import68.PreloadAllModules {
    if ((this.__PreloadAllModules_90 == null)) { (this.__PreloadAllModules_90 = new import68.PreloadAllModules()); }
    return this.__PreloadAllModules_90;
  }
  get _ROUTER_INITIALIZER_91():any {
    if ((this.__ROUTER_INITIALIZER_91 == null)) { (this.__ROUTER_INITIALIZER_91 = import22.initialRouterNavigation(this._Router_85,this._ApplicationRef_54,this._RouterPreloader_89,this._ROUTER_CONFIGURATION_78)); }
    return this.__ROUTER_INITIALIZER_91;
  }
  get _APP_BOOTSTRAP_LISTENER_92():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_92 == null)) { (this.__APP_BOOTSTRAP_LISTENER_92 = [this._ROUTER_INITIALIZER_91]); }
    return this.__APP_BOOTSTRAP_LISTENER_92;
  }
  get _ErrorService_93():import69.ErrorService {
    if ((this.__ErrorService_93 == null)) { (this.__ErrorService_93 = new import69.ErrorService()); }
    return this.__ErrorService_93;
  }
  get _AuthService_94():import70.AuthService {
    if ((this.__AuthService_94 == null)) { (this.__AuthService_94 = new import70.AuthService(this._Http_77,this._ErrorService_93)); }
    return this.__AuthService_94;
  }
  get _NewsService_95():import71.NewsService {
    if ((this.__NewsService_95 == null)) { (this.__NewsService_95 = new import71.NewsService(this._Http_77,this._ErrorService_93)); }
    return this.__NewsService_95;
  }
  get _ProfileService_96():import72.ProfileService {
    if ((this.__ProfileService_96 == null)) { (this.__ProfileService_96 = new import72.ProfileService(this._Http_77,this._ErrorService_93)); }
    return this.__ProfileService_96;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._NgbAlertModule_1 = new import3.NgbAlertModule();
    this._NgbButtonsModule_2 = new import4.NgbButtonsModule();
    this._NgbCollapseModule_3 = new import5.NgbCollapseModule();
    this._NgbProgressbarModule_4 = new import6.NgbProgressbarModule();
    this._NgbTooltipModule_5 = new import7.NgbTooltipModule();
    this._NgbTypeaheadModule_6 = new import8.NgbTypeaheadModule();
    this._NgbAccordionModule_7 = new import9.NgbAccordionModule();
    this._NgbCarouselModule_8 = new import10.NgbCarouselModule();
    this._InternalFormsSharedModule_9 = new import11.InternalFormsSharedModule();
    this._FormsModule_10 = new import12.FormsModule();
    this._NgbDatepickerModule_11 = new import13.NgbDatepickerModule();
    this._NgbDropdownModule_12 = new import14.NgbDropdownModule();
    this._NgbModalModule_13 = new import15.NgbModalModule();
    this._NgbPaginationModule_14 = new import16.NgbPaginationModule();
    this._NgbPopoverModule_15 = new import17.NgbPopoverModule();
    this._NgbRatingModule_16 = new import18.NgbRatingModule();
    this._NgbTabsetModule_17 = new import19.NgbTabsetModule();
    this._NgbTimepickerModule_18 = new import20.NgbTimepickerModule();
    this._NgbRootModule_19 = new import21.NgbRootModule();
    this._ROUTER_FORROOT_GUARD_20 = import22.provideForRootGuard(this.parent.get(import100.Router,(null as any)));
    this._RouterModule_21 = new import22.RouterModule(this._ROUTER_FORROOT_GUARD_20);
    this._FileUploadModule_22 = new import23.FileUploadModule();
    this._UploadModule_23 = new import24.UploadModule();
    this._ApplicationModule_24 = new import25.ApplicationModule();
    this._BrowserModule_25 = new import26.BrowserModule(this.parent.get(import26.BrowserModule,(null as any)));
    this._HttpModule_26 = new import27.HttpModule();
    this._AppModule_27 = new import1.AppModule();
    this._ErrorHandler_50 = import26.errorHandler();
    this._ApplicationInitStatus_51 = new import49.ApplicationInitStatus(this.parent.get(import49.APP_INITIALIZER,(null as any)));
    this._Testability_52 = new import50.Testability(this.parent.get(import90.NgZone));
    this._ApplicationRef__53 = new import51.ApplicationRef_(this.parent.get(import90.NgZone),this.parent.get(import101.Console),this,this._ErrorHandler_50,this,this._ApplicationInitStatus_51,this.parent.get(import50.TestabilityRegistry,(null as any)),this._Testability_52);
    this._NoPreloading_87 = new import68.NoPreloading();
    this._PreloadingStrategy_88 = this._NoPreloading_87;
    this._RouterPreloader_89 = new import68.RouterPreloader(this._Router_85,this._NgModuleFactoryLoader_83,this._Compiler_55,this,this._PreloadingStrategy_88);
    return this._AppModule_27;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.NgbAlertModule)) { return this._NgbAlertModule_1; }
    if ((token === import4.NgbButtonsModule)) { return this._NgbButtonsModule_2; }
    if ((token === import5.NgbCollapseModule)) { return this._NgbCollapseModule_3; }
    if ((token === import6.NgbProgressbarModule)) { return this._NgbProgressbarModule_4; }
    if ((token === import7.NgbTooltipModule)) { return this._NgbTooltipModule_5; }
    if ((token === import8.NgbTypeaheadModule)) { return this._NgbTypeaheadModule_6; }
    if ((token === import9.NgbAccordionModule)) { return this._NgbAccordionModule_7; }
    if ((token === import10.NgbCarouselModule)) { return this._NgbCarouselModule_8; }
    if ((token === import11.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_9; }
    if ((token === import12.FormsModule)) { return this._FormsModule_10; }
    if ((token === import13.NgbDatepickerModule)) { return this._NgbDatepickerModule_11; }
    if ((token === import14.NgbDropdownModule)) { return this._NgbDropdownModule_12; }
    if ((token === import15.NgbModalModule)) { return this._NgbModalModule_13; }
    if ((token === import16.NgbPaginationModule)) { return this._NgbPaginationModule_14; }
    if ((token === import17.NgbPopoverModule)) { return this._NgbPopoverModule_15; }
    if ((token === import18.NgbRatingModule)) { return this._NgbRatingModule_16; }
    if ((token === import19.NgbTabsetModule)) { return this._NgbTabsetModule_17; }
    if ((token === import20.NgbTimepickerModule)) { return this._NgbTimepickerModule_18; }
    if ((token === import21.NgbRootModule)) { return this._NgbRootModule_19; }
    if ((token === import22.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_20; }
    if ((token === import22.RouterModule)) { return this._RouterModule_21; }
    if ((token === import23.FileUploadModule)) { return this._FileUploadModule_22; }
    if ((token === import24.UploadModule)) { return this._UploadModule_23; }
    if ((token === import25.ApplicationModule)) { return this._ApplicationModule_24; }
    if ((token === import26.BrowserModule)) { return this._BrowserModule_25; }
    if ((token === import27.HttpModule)) { return this._HttpModule_26; }
    if ((token === import1.AppModule)) { return this._AppModule_27; }
    if ((token === import102.LOCALE_ID)) { return this._LOCALE_ID_28; }
    if ((token === import28.NgLocalization)) { return this._NgLocalization_29; }
    if ((token === import29.RadioControlRegistry)) { return this._RadioControlRegistry_30; }
    if ((token === import30.NgbModalStack)) { return this._NgbModalStack_31; }
    if ((token === import31.NgbModal)) { return this._NgbModal_32; }
    if ((token === import32.NgbAlertConfig)) { return this._NgbAlertConfig_33; }
    if ((token === import33.NgbProgressbarConfig)) { return this._NgbProgressbarConfig_34; }
    if ((token === import34.NgbTooltipConfig)) { return this._NgbTooltipConfig_35; }
    if ((token === import35.NgbTypeaheadConfig)) { return this._NgbTypeaheadConfig_36; }
    if ((token === import36.NgbAccordionConfig)) { return this._NgbAccordionConfig_37; }
    if ((token === import37.NgbCarouselConfig)) { return this._NgbCarouselConfig_38; }
    if ((token === import38.NgbCalendar)) { return this._NgbCalendar_39; }
    if ((token === import39.NgbDatepickerI18n)) { return this._NgbDatepickerI18n_40; }
    if ((token === import40.NgbDateParserFormatter)) { return this._NgbDateParserFormatter_41; }
    if ((token === import41.NgbDatepickerService)) { return this._NgbDatepickerService_42; }
    if ((token === import42.NgbDatepickerConfig)) { return this._NgbDatepickerConfig_43; }
    if ((token === import43.NgbDropdownConfig)) { return this._NgbDropdownConfig_44; }
    if ((token === import44.NgbPaginationConfig)) { return this._NgbPaginationConfig_45; }
    if ((token === import45.NgbPopoverConfig)) { return this._NgbPopoverConfig_46; }
    if ((token === import46.NgbRatingConfig)) { return this._NgbRatingConfig_47; }
    if ((token === import47.NgbTabsetConfig)) { return this._NgbTabsetConfig_48; }
    if ((token === import48.NgbTimepickerConfig)) { return this._NgbTimepickerConfig_49; }
    if ((token === import103.ErrorHandler)) { return this._ErrorHandler_50; }
    if ((token === import49.ApplicationInitStatus)) { return this._ApplicationInitStatus_51; }
    if ((token === import50.Testability)) { return this._Testability_52; }
    if ((token === import51.ApplicationRef_)) { return this._ApplicationRef__53; }
    if ((token === import51.ApplicationRef)) { return this._ApplicationRef_54; }
    if ((token === import52.Compiler)) { return this._Compiler_55; }
    if ((token === import87.APP_ID)) { return this._APP_ID_56; }
    if ((token === import104.DOCUMENT)) { return this._DOCUMENT_57; }
    if ((token === import53.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_58; }
    if ((token === import54.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_59; }
    if ((token === import54.EventManager)) { return this._EventManager_60; }
    if ((token === import55.DomSharedStylesHost)) { return this._DomSharedStylesHost_61; }
    if ((token === import105.AnimationDriver)) { return this._AnimationDriver_62; }
    if ((token === import56.DomRootRenderer)) { return this._DomRootRenderer_63; }
    if ((token === import106.RootRenderer)) { return this._RootRenderer_64; }
    if ((token === import57.DomSanitizer)) { return this._DomSanitizer_65; }
    if ((token === import107.Sanitizer)) { return this._Sanitizer_66; }
    if ((token === import58.ViewUtils)) { return this._ViewUtils_67; }
    if ((token === import108.IterableDiffers)) { return this._IterableDiffers_68; }
    if ((token === import109.KeyValueDiffers)) { return this._KeyValueDiffers_69; }
    if ((token === import55.SharedStylesHost)) { return this._SharedStylesHost_70; }
    if ((token === import59.Title)) { return this._Title_71; }
    if ((token === import60.BrowserXhr)) { return this._BrowserXhr_72; }
    if ((token === import61.ResponseOptions)) { return this._ResponseOptions_73; }
    if ((token === import110.XSRFStrategy)) { return this._XSRFStrategy_74; }
    if ((token === import62.XHRBackend)) { return this._XHRBackend_75; }
    if ((token === import63.RequestOptions)) { return this._RequestOptions_76; }
    if ((token === import111.Http)) { return this._Http_77; }
    if ((token === import22.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_78; }
    if ((token === import93.LocationStrategy)) { return this._LocationStrategy_79; }
    if ((token === import64.Location)) { return this._Location_80; }
    if ((token === import65.UrlSerializer)) { return this._UrlSerializer_81; }
    if ((token === import66.RouterOutletMap)) { return this._RouterOutletMap_82; }
    if ((token === import112.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_83; }
    if ((token === import113.ROUTES)) { return this._ROUTES_84; }
    if ((token === import100.Router)) { return this._Router_85; }
    if ((token === import114.ActivatedRoute)) { return this._ActivatedRoute_86; }
    if ((token === import68.NoPreloading)) { return this._NoPreloading_87; }
    if ((token === import68.PreloadingStrategy)) { return this._PreloadingStrategy_88; }
    if ((token === import68.RouterPreloader)) { return this._RouterPreloader_89; }
    if ((token === import68.PreloadAllModules)) { return this._PreloadAllModules_90; }
    if ((token === import22.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_91; }
    if ((token === import87.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_92; }
    if ((token === import69.ErrorService)) { return this._ErrorService_93; }
    if ((token === import70.AuthService)) { return this._AuthService_94; }
    if ((token === import71.NewsService)) { return this._NewsService_95; }
    if ((token === import72.ProfileService)) { return this._ProfileService_96; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__53.ngOnDestroy();
    this._RouterPreloader_89.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);